# =============================================================================
# TrakBridge Docker Compose Configuration
# =============================================================================
#
# Usage:
#   docker-compose up                         # App only (requires external DB or SQLite)
#   docker-compose --profile postgres up      # App + PostgreSQL
#   docker-compose --profile mysql up         # App + MySQL
#   docker-compose --profile nginx up         # App + Nginx reverse proxy
#   docker-compose --profile postgres --profile nginx up  # Full stack
#
# Configuration:
#   Edit the 'x-environment' section below to customize your deployment
#
# =============================================================================

# =============================================================================
# CONFIGURATION SECTION - Edit these values for your deployment
# =============================================================================
x-environment: &common-environment
  # Application Settings
  APP_VERSION: "latest"
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
  APP_PORT: "5000"
  
  # Database Configuration - Postresql
  DB_TYPE: "postgresql" 
  DB_HOST: "postgres"
  DB_PORT: "5432" 
  DB_NAME: "trakbridge"
  DB_USER: "trakbridge"
  
# Database Configuration - MySQL
#  DB_TYPE: "mysql" 
#  DB_HOST: "mysql"
#  DB_PORT: "3306"
#  DB_NAME: "trakbridge"
#  DB_USER: "trakbridge"

# Database Configuration - SQLite
#  DB_TYPE: "sqlite"


  # Application Performance
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  MAX_WORKER_THREADS: "4"
  DEFAULT_POLL_INTERVAL: "120"
  HTTP_TIMEOUT: "30"
  
  # External Database Ports (uncomment if needed)
  # POSTGRES_PORT: "5432"
  # MYSQL_PORT: "3306"

# Secret file paths - customize if needed
x-secrets: &common-secrets
  DB_PASSWORD_FILE: "./secrets/db_password"
  SECRET_KEY_FILE: "./secrets/secret_key"
  TB_MASTER_KEY_FILE: "./secrets/tb_master_key"

version: '3.8'

services:
  # =============================================================================
  # TrakBridge Application
  # =============================================================================
  trakbridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: emfoursolutions/trakbridge:latest
    container_name: trakbridge
    restart: unless-stopped

    environment:
      <<: *common-environment
      
    secrets:
      - db_password
      - secret_key
      - tb_master_key

    ports:
      - "5000:5000"

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./secrets:/app/secrets

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    depends_on:
      postgres:
        condition: service_healthy
        required: false
      mysql:
        condition: service_healthy
        required: false

    networks:
      - trakbridge

  # =============================================================================
  # PostgreSQL Database (Optional)
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: trakbridge-postgres
    restart: unless-stopped
    profiles: ["postgres"]

    environment:
      POSTGRES_DB: trakbridge
      POSTGRES_USER: trakbridge
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_password

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-scripts/postgres:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trakbridge -d trakbridge"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - trakbridge

  # =============================================================================
  # MySQL Database (Optional)
  # =============================================================================
  mysql:
    image: mysql:8.0
    container_name: trakbridge-mysql
    restart: unless-stopped
    profiles: ["mysql"]

    environment:
      MYSQL_DATABASE: trakbridge
      MYSQL_USER: trakbridge
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_password

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init-scripts/mysql:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - trakbridge

  # =============================================================================
  # Nginx Reverse Proxy (Optional)
  # =============================================================================
  nginx:
    image: nginx:alpine
    container_name: trakbridge-nginx
    restart: unless-stopped
    profiles: ["nginx"]

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx

    depends_on:
      app:
        condition: service_healthy

    networks:
      - trakbridge

# =============================================================================
# Networks & Volumes
# =============================================================================
networks:
  trakbridge:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local

# =============================================================================
# Secrets
# =============================================================================
secrets:
  db_password:
    file: ./secrets/db_password
  secret_key:
    file: ./secrets/secret_key
  tb_master_key:
    file: ./secrets/tb_master_key