"""Add authentication tables for users and sessions

Revision ID: 0a9c5469abc6
Revises: e2f64ceef0b8
Create Date: 2025-07-27 07:19:04.425400

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a9c5469abc6"
down_revision = "e2f64ceef0b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("streams", schema=None) as batch_op:
        batch_op.alter_column(
            "cot_type_mode", existing_type=sa.VARCHAR(length=20), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("streams", schema=None) as batch_op:
        batch_op.alter_column(
            "cot_type_mode", existing_type=sa.VARCHAR(length=20), nullable=False
        )

    # ### end Alembic commands ###
