"""Add authentication tables for users and sessions

Revision ID: 0a9c5469abc6
Revises: e2f64ceef0b8
Create Date: 2025-07-27 07:19:04.425400

"""

import sqlalchemy as sa
from alembic import op
from migrations.migration_utils import table_exists, column_exists, safe_alter_column

# revision identifiers, used by Alembic.
revision = "0a9c5469abc6"
down_revision = "e2f64ceef0b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely alter column only if table and column exist
    if table_exists("streams") and column_exists("streams", "cot_type_mode"):
        safe_alter_column(
            "streams",
            "cot_type_mode",
            existing_type=sa.VARCHAR(length=20),
            nullable=True,
            schema=None,
        )
    else:
        print(
            "WARNING: Table 'streams' or column 'cot_type_mode' does not exist. Skipping column alteration."
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely alter column only if table and column exist
    if table_exists("streams") and column_exists("streams", "cot_type_mode"):
        safe_alter_column(
            "streams",
            "cot_type_mode",
            existing_type=sa.VARCHAR(length=20),
            nullable=False,
            schema=None,
        )
    else:
        print(
            "WARNING: Table 'streams' or column 'cot_type_mode' does not exist. Skipping column alteration."
        )

    # ### end Alembic commands ###
