"""Add provider field to user_sessions table

Revision ID: 3120f5bf60a4
Revises: 0a9c5469abc6
Create Date: 2025-07-28 09:51:48.726581

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3120f5bf60a4"
down_revision = "0a9c5469abc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "provider",
                sa.Enum("LOCAL", "OIDC", "LDAP", name="authprovider"),
                nullable=True,
            )
        )

    # Update existing rows to have 'LOCAL' as default provider
    op.execute("UPDATE user_sessions SET provider = 'LOCAL' WHERE provider IS NULL")

    # Now make the column NOT NULL
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.alter_column("provider", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_column("provider")

    # ### end Alembic commands ###
