"""add_ca_cert_to_streams

Revision ID: 54faa293e582
Revises: add_inbound_stream_fields
Create Date: 2026-05-02 09:56:12.684326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54faa293e582'
down_revision = 'add_inbound_stream_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ca_cert', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('ca_cert_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('ca_cert_filename')
        batch_op.drop_column('ca_cert')

    # ### end Alembic commands ###
