"""Add TLS version selection to TAK servers

Revision ID: c530e1fd8e8d
Revises: b1c2d3e4f5g6
Create Date: 2025-09-10 19:44:05.466972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c530e1fd8e8d'
down_revision = 'b1c2d3e4f5g6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tak_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tls_version', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tak_servers', schema=None) as batch_op:
        batch_op.drop_column('tls_version')

    # ### end Alembic commands ###
