"""Add TLS version selection to TAK servers

Revision ID: c530e1fd8e8d
Revises: b1c2d3e4f5g6
Create Date: 2025-09-10 19:44:05.466972

"""
from alembic import op
import sqlalchemy as sa
from migrations.migration_utils import column_exists


# revision identifiers, used by Alembic.
revision = 'c530e1fd8e8d'
down_revision = 'b1c2d3e4f5g6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the column if it doesn't already exist
    if not column_exists('tak_servers', 'tls_version'):
        with op.batch_alter_table('tak_servers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('tls_version', sa.String(length=10), nullable=False))
        print("Added tls_version column to tak_servers table")
    else:
        print("tls_version column already exists in tak_servers table - skipping")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the column if it exists
    if column_exists('tak_servers', 'tls_version'):
        with op.batch_alter_table('tak_servers', schema=None) as batch_op:
            batch_op.drop_column('tls_version')
        print("Dropped tls_version column from tak_servers table")
    else:
        print("tls_version column doesn't exist in tak_servers table - skipping")

    # ### end Alembic commands ###
