"""Add config_version field to streams table for worker coordination

Revision ID: eff2e20f64e2
Revises: f085153337e8
Create Date: 2025-09-18 19:08:34.640736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff2e20f64e2'
down_revision = 'f085153337e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callsign_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callsign_mappings_enabled'))
        batch_op.drop_index(batch_op.f('ix_callsign_mappings_stream_enabled'))

    # Add config_version field to streams table for worker coordination
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_version', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove config_version field from streams table
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('config_version')

    with op.batch_alter_table('callsign_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callsign_mappings_stream_enabled'), ['stream_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_callsign_mappings_enabled'), ['enabled'], unique=False)

    # ### end Alembic commands ###
