# TrakBridge Performance Configuration
# Phase 1B: Configuration & Fallbacks for Parallel Processing

parallel_processing:
  # Enable or disable parallel processing entirely
  enabled: true
  
  # Minimum number of locations to trigger parallel processing
  # Below this threshold, serial processing will be used
  batch_size_threshold: 10
  
  # Maximum number of concurrent tasks for parallel processing
  # Prevents overwhelming the system with too many simultaneous operations
  max_concurrent_tasks: 50
  
  # Automatically fallback to serial processing if parallel fails
  fallback_on_error: true
  
  # Processing timeout in seconds (0 = no timeout)
  processing_timeout: 30.0
  
  # Enable detailed performance logging
  enable_performance_logging: true

# Circuit breaker configuration for fault tolerance
circuit_breaker:
  # Number of consecutive failures before opening circuit
  failure_threshold: 3
  
  # Time to wait before attempting to close circuit (seconds)
  recovery_timeout: 60.0
  
  # Enable circuit breaker pattern
  enabled: true

# Performance monitoring and statistics
monitoring:
  # Track fallback statistics for alerting
  track_fallback_statistics: true
  
  # Maximum number of statistics entries to keep in memory
  max_statistics_entries: 1000
  
  # Reset statistics after this many seconds (0 = never reset)
  statistics_reset_interval: 3600

# Queue Management Configuration (Phase 2)
queue:
  # Maximum events per queue (prevents unbounded growth)
  max_size: 500
  
  # Events per transmission batch
  batch_size: 20
  
  # Overflow strategy when queue is full
  # Options: drop_oldest, drop_newest, block
  overflow_strategy: "drop_oldest"
  
  # Flush queue immediately on configuration changes
  flush_on_config_change: true

# Transmission Configuration
transmission:
  # Maximum wait time to fill batch (milliseconds)
  batch_timeout_ms: 100
  
  # How often to check for new events (milliseconds)
  # Phase 3: Optimized from 50ms to 100ms to reduce polling overhead
  queue_check_interval_ms: 100

# Monitoring Configuration
monitoring:
  # Enable queue size logging
  log_queue_stats: true

  # Log warning when queue exceeds this threshold
  queue_warning_threshold: 400

# Performance regression detection for queue optimizer
regression_detection:
  # Memory usage regression threshold (as percentage, e.g., 0.40 = 40%)
  memory_threshold: 0.40

  # CPU usage regression threshold (as percentage, e.g., 0.40 = 40%)
  cpu_threshold: 0.40

  # Throughput regression threshold (as percentage, e.g., 0.40 = 40%)
  throughput_threshold: 0.40

  # Enable regression detection
  enabled: true

  # Number of baseline samples to collect for comparison
  baseline_samples: 10

# Environment variable overrides
# These can be set to override configuration values:
# TRAKBRIDGE_PARALLEL_ENABLED=true/false
# TRAKBRIDGE_BATCH_SIZE_THRESHOLD=number
# TRAKBRIDGE_MAX_CONCURRENT_TASKS=number
# TRAKBRIDGE_FALLBACK_ON_ERROR=true/false
# Queue configuration overrides:
# QUEUE_MAX_SIZE=500
# QUEUE_BATCH_SIZE=20
# QUEUE_OVERFLOW_STRATEGY=drop_oldest
# QUEUE_FLUSH_ON_CONFIG_CHANGE=true
# TRANSMISSION_BATCH_TIMEOUT_MS=100
# TRANSMISSION_QUEUE_CHECK_INTERVAL_MS=100
# MONITORING_LOG_QUEUE_STATS=true
# MONITORING_QUEUE_WARNING_THRESHOLD=400
# Regression detection overrides:
# REGRESSION_MEMORY_THRESHOLD=0.40
# REGRESSION_CPU_THRESHOLD=0.40
# REGRESSION_THROUGHPUT_THRESHOLD=0.40
# REGRESSION_DETECTION_ENABLED=true/false